travis:
  secure:
    BINSTAR_TOKEN: Hp07dEmVACFsiSXimUEnMrbYszu29dAjZoF3J22VAK6vMI63EB6YXmb9+iDIbp8wNKYn2pB7FI2AzRSq2Qu4/i9dvOLPXAdWcBhkmidG7S4MXgTxzMXLmjcWFbgmJyqX29fQHgR/PhmvoEOBvQpzAE3glIemd9TsBxW+/Qx3jg7ib726UAWmMCn5D6FNgiDm5RiiSwrpTJd/LFBiMZ4wI/2yIWCFBQEGIt9V2nkuG9Pga28maIMXeYjZSm8fg9cEpGPbjIpIw6kW4vbV8036PfMsHCj0TUrQQTpbz3kCkJg0UXBKQSJBWhfBs/Yk9OZxHzmIntlGe8FJRnLrDzTZUaRHBLXcIJGmVMMh6FJTEBeDnob9zrRt+jxTzIQUHmqyd1nyfWH3O78HtlMmqoW6gGwVuvwhyOvb33g8SzTjF+FJGF36ngwB6lOEZFU1RxCvanKNFKJZGVBAd/ACX/1VkjTd8f096lCDqG1E4EYYpU2T6Nq59t5WWpyF2vyCU4opJKdQDSj0zrdAMIOr+E57t48BNPcQPBrk61zqwurScWgYFLBX/lnZmVry6TBi8hy89wsPdRl/cOmg+tXRfrj5eG4kc0i76kHP0wh0KFV6FZy8szg6IHsXI65b8oprGwb27RPZiODpuD4lkJNSdZqYhtOBV1SzuR186s5c4OA8drA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
